export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_TOKEN="ADD_TOKEN";
export const REMOVE_TOKEN="REMOVE_TOKEN";
export const FILTER_PRODUCTS="FILTER_PRODUCTS";
export const ADD_PRODUCT="ADD_PRODUCT"
export const SEARCH_PRODUCTS="SEARCH_PRODUCTS"
export const SET_PRODUCTS="SET_PRODUCTS"